version: '3.4'

services:
  atlassian-exporter:
    image: jenkins-exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app/export:/usr/src/app/export
    command: >
      bash -c "python jenkins-exporter.py -c jenkins_conn_elwillie.json -a export_all_jenkins_users
      && python jenkins-exporter.py -c jenkins_conn_elwillie.json -a export_all_jenkins_plugins
      && python jenkins-exporter.py -c jenkins_conn_elwillie.json -a export_all_jenkins_jobs
      && python jenkins-exporter.py -c jenkins_conn_elwillie.json -a export_all_jenkins_rbas_global_roles
      && python jenkins-exporter.py -c jenkins_conn_elwillie.json -a export_all_jenkins_rbas_project_roles"
